// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzhfy_jhkpa2-8EBo2Qr_3eeRyNyZvTEA',
    appId: '1:818987862063:android:69ca2441801a697dd7deda',
    messagingSenderId: '818987862063',
    projectId: 'sar-track',
    databaseURL: 'https://sar-track-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sar-track.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh7DYWwFnPMh3_Ep9DRbemx_XQKMVfwj0',
    appId: '1:818987862063:web:c6bd2834f9e9d690d7deda',
    messagingSenderId: '818987862063',
    projectId: 'sar-track',
    authDomain: 'sar-track.firebaseapp.com',
    databaseURL: 'https://sar-track-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sar-track.firebasestorage.app',
    measurementId: 'G-PM9P6RKK4T',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8MxGTNkcbNOJlmYUNv2tm3gXzoZK6WL4',
    appId: '1:818987862063:ios:b364eca82630ddd1d7deda',
    messagingSenderId: '818987862063',
    projectId: 'sar-track',
    databaseURL: 'https://sar-track-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sar-track.firebasestorage.app',
    iosClientId: '818987862063-0ctf9uvsr931jve2io0pfg0a2t15o2si.apps.googleusercontent.com',
    iosBundleId: 'com.example.sarTrack',
  );

}